language: julia
os:
    # Temporarily commenting out osx because of Homebrew installation issue
    # of gcc 8.x. This causes the HDF5 build to attempt to build it from scratch
    # by downloading all of xcode which Travis CI then kills because it takes too long.
    # Refer to Matt Bauman's comment on JuliaIO/HDF5.jl issue 483, and
    # Andreas Noack's issue 27751 on Homebrew/homebrew-core.
    #- osx
    - linux
julia:
    - 1
    - 1.1 # Test 1.1 b/c some branches for new features still use 1.1
    # - 1.4 # Ensure tests pass on the second to most recent version of Julia
notifications:
    email: false
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
script:
    - julia --color=yes -e 'using Pkg; Pkg.build()'
    - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
    # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    # - julia --color=yes -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("DSGE")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
- julia -e 'using Pkg; Pkg.add("Documenter")'
- julia -e 'using Pkg; cd(Pkg.dir("DSGE")); include(joinpath("docs", "make.jl"))'

# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1
#       os: linux
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
#                                                Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
