language: julia
os:
    # Temporarily commenting out osx because of Homebrew installation issue
    # of gcc 8.x. This causes the HDF5 build to attempt to build it from scratch
    # by downloading all of xcode which Travis CI then kills because it takes too long.
    # Refer to Matt Bauman's comment on JuliaIO/HDF5.jl issue 483, and
    # Andreas Noack's issue 27751 on Homebrew/homebrew-core.
    - osx
    - linux
julia:
    - 0.7.0
notifications:
    email: false
addons:
  apt:
    packages:
    - hdf5-tools
    - libnlopt0
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --color=yes -e 'Pkg.clone(pwd()); Pkg.build("DSGE"); Pkg.test("DSGE"; coverage=true)'
branches:
  only:
    - master
    - gh-pages
after_success:
- julia -e 'Pkg.add("Documenter")'
- julia -e 'cd(Pkg.dir("DSGE")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
- julia -e 'cd(Pkg.dir("DSGE")); include(joinpath("docs", "make.jl"))'

jobs:
  include:
    - stage: "Documentation"
      julia: 0.7
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
